config/routes.rb
Rails.application.routes.draw do
  resources :phone_numbers

  resources :schools

  resources :cities

  resources :periods

  resources :holidays

  get 'page/index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :federal_states

  resources :countries

  root 'page#index'

end

app/models/holiday.rb
class Holiday < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  # Associations
  #

  # Validations
  #
  validates :name,
            presence: true,
            uniqueness: true

  def to_s
    name.to_s
  end

end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :set_and_authorize_holiday, only: [:show, :edit, :update, :destroy]

  after_filter :verify_authorized,  except: :index
  after_filter :verify_policy_scoped, only: :index

  def index
    @holidays = policy_scope(Holiday.all)
    fresh_when etag: [I18n.locale, current_user, cache_key_for_all(Holiday)]
  end

  def show
    fresh_when etag: [I18n.locale, current_user, @holiday]
  end

  def new
    @holiday = Holiday.new
    authorize @holiday, :new?
  end

  def edit
  end

  def create
    @holiday = Holiday.new(holiday_params)
    authorize @holiday, :create?

    if @holiday.save
      redirect_to @holiday, notice: 'Holiday was successfully created.'
    else
      render :new
    end
  end

  def update
    if @holiday.update(holiday_params)
      redirect_to @holiday, notice: 'Holiday was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @holiday.destroy
    redirect_to holidays_url, notice: 'Holiday was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_and_authorize_holiday
      @holiday = Holiday.friendly.find(params[:id])
      authorize @holiday, "#{action_name}?".to_sym
    end

    # Only allow a trusted parameter "white list" through.
    def holiday_params
      params.require(:holiday).permit(:name)
    end
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/_form.html.erb
<%= form_for @holiday, html: { class: "pure-form pure-form-aligned" } do |f| %>
  <% if @holiday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@holiday.errors.count, "error") %> prohibited this holiday from being saved:</h2>

      <ul>
      <% @holiday.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </fieldset>
  <fieldset>
    <%= f.submit class: "pure-button pure-button-primary" %>
  </fieldset>
<% end %>

app/views/holidays/edit.html.erb
<h1>Editing Holiday</h1>

<%= render 'form' %>

app/views/holidays/index.html.erb
<% cache [I18n.locale, current_user, cache_key_for_all(Holiday)] do %>
  <h1>Listing Holidays</h1>

  <table class="pure-table pure-table-horizontal">
    <thead>
      <tr>
          <th>Name</th>
          <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @holidays.each do |holiday| %>
        <tr>
            <td><%= holiday.name %></td>
            <td><%= link_to 'Show', holiday, class: policy(holiday).show? ? 'pure-button':'pure-button pure-button-disabled' %></td>
          <td><%= link_to 'Edit', edit_holiday_path(holiday), class: policy(holiday).edit? ? 'pure-button':'pure-button pure-button-disabled' %></td>
          <td><%= link_to 'Destroy', holiday, method: :delete, data: { confirm: 'Are you sure?' }, class: policy(holiday).destroy? ? 'pure-button':'pure-button pure-button-disabled' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Holiday', new_holiday_path, class: policy(Holiday.new).new? ? 'pure-button':'pure-button pure-button-disabled' %>
<% end %>

app/views/holidays/new.html.erb
<h1>New Holiday</h1>

<%= render 'form' %>

app/views/holidays/show.html.erb
<% cache [I18n.locale, current_user, @holiday] do %>
  <table class="pure-table pure-table-horizontal">
    <tbody>
        <tr>
        <td><strong>Name:</strong></td>
        <td><%= @holiday.name %></td>
      </tr>
      </tbody>
  </table>
<% end %>