config/routes.rb
Rails.application.routes.draw do
  resources :phone_numbers

  resources :schools

  resources :cities

  resources :periods

  resources :holidays

  get 'page/index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :federal_states

  resources :countries

  root 'page#index'

end

app/models/federal_state.rb
class FederalState < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  # Associations
  #
  belongs_to :country, touch: true
  has_many :periods, as: :periodable, dependent: :destroy
  has_many :cities, dependent: :destroy
  has_many :schools, through: :cities

  # Validations
  #
  validates :country,
            presence: true

  validates :name,
            presence: true,
            uniqueness: { scope: :country,
                          message: "should be unique per country" }


  def to_s
    name.to_s
  end

end

app/controllers/federal_states_controller.rb
class FederalStatesController < ApplicationController
  before_action :set_and_authorize_federal_state, only: [:show, :edit, :update, :destroy]

  after_filter :verify_authorized,  except: :index
  after_filter :verify_policy_scoped, only: :index

  # GET /federal_states
  def index
    @federal_states = policy_scope(FederalState.all)
  end

  # GET /federal_states/1
  def show
  end

  # GET /federal_states/new
  def new
    @federal_state = FederalState.new
    authorize @federal_state, :new?
  end

  # GET /federal_states/1/edit
  def edit
  end

  # POST /federal_states
  def create
    @federal_state = FederalState.new(federal_state_params)
    authorize @federal_state, :create?

    if @federal_state.save
      redirect_to @federal_state, notice: 'Federal state was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /federal_states/1
  def update
    if @federal_state.update(federal_state_params)
      redirect_to @federal_state, notice: 'Federal state was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /federal_states/1
  def destroy
    @federal_state.destroy
    redirect_to federal_states_url, notice: 'Federal state was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_and_authorize_federal_state
      @federal_state = FederalState.friendly.find(params[:id])
      authorize @federal_state, "#{action_name}?".to_sym
    end

    # Only allow a trusted parameter "white list" through.
    def federal_state_params
      params.require(:federal_state).permit(:country_id, :name, :slug)
    end
end

app/helpers/federal_states_helper.rb
module FederalStatesHelper
end

app/views/federal_states/_form.html.erb
<%= form_for @federal_state, html: { class: "pure-form pure-form-aligned" } do |f| %>
  <% if @federal_state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@federal_state.errors.count, "error") %> prohibited this federal_state from being saved:</h2>

      <ul>
      <% @federal_state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <%= f.label :country_id %><br>
    <%= f.text_field :country_id %>
  </fieldset>
  <fieldset>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </fieldset>
  <fieldset>
    <%= f.submit class: "pure-button pure-button-primary" %>
  </fieldset>
<% end %>

app/views/federal_states/edit.html.erb
<h1>Editing Federal State</h1>

<%= render 'form' %>

app/views/federal_states/index.html.erb
<h1>Listing Federal States</h1>

<table class="pure-table pure-table-horizontal">
  <thead>
    <tr>
      <th>Country</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @federal_states.each do |federal_state| %>
      <tr>
        <td><%= federal_state.country %></td>
        <td><%= federal_state.name %></td>
        <td><%= link_to 'Show', federal_state, class: policy(federal_state).show? ? 'pure-button':'pure-button pure-button-disabled' %></td>
        <td><%= link_to 'Edit', edit_federal_state_path(federal_state), class: policy(federal_state).edit? ? 'pure-button':'pure-button pure-button-disabled' %></td>
        <td><%= link_to 'Destroy', federal_state, method: :delete, data: { confirm: 'Are you sure?' }, class: policy(federal_state).destroy? ? 'pure-button':'pure-button pure-button-disabled' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Federal state', new_federal_state_path, class: policy(FederalState.new).new? ? 'pure-button':'pure-button pure-button-disabled' %>

app/views/federal_states/new.html.erb
<h1>New Federal State</h1>

<%= render 'form' %>

app/views/federal_states/show.html.erb
<table class="pure-table pure-table-horizontal">
  <tbody>
    <tr>
      <td><strong>Country:</strong></td>
      <td><%= @federal_state.country %></td>
    </tr>
    <tr>
      <td><strong>Name:</strong></td>
      <td><%= @federal_state.name %></td>
    </tr>
  </tbody>
</table>