config/routes.rb
Rails.application.routes.draw do
  resources :phone_numbers

  resources :schools

  resources :cities

  resources :periods

  resources :holidays

  get 'page/index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :federal_states

  resources :countries

  root 'page#index'

end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  # Associations
  #
  belongs_to :phone_numberable, polymorphic: true, touch: true

  # Callbacks
  #
  before_validation :format_value

  # Validations
  #
  validates :name,
            presence: true

  validates :value,
            presence: true,
            uniqueness: { scope: [:name, :phone_numberable],
              message: "should be unique per instance" },
            format: { with: /\A\+49\-[1-9][0-9]+\-[0-9][0-9][0-9]+\z/,
              message: "only allows +49-xxx-xxxxx format" }

  validates :phone_numberable,
            presence: true

  def to_s
    "#{value} (#{name})"
  end

  private
  def format_value
    # This only works for German phone numbers.
    # There is room for improvement.
    #
    case self.value.to_s.strip
    when /\A\(0([1-9][0-9]+)\)([0-9]+)\z/
      self.value = "+49-#{$1}-#{$2}"
    when /\A0([1-9][0-9]+)[-\/ ]([0-9]+)\z/
      self.value = "+49-#{$1}-#{$2}"
    end
  end

end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_action :set_and_authorize_phone_number, only: [:show, :edit, :update, :destroy]

  after_filter :verify_authorized,  except: :index
  after_filter :verify_policy_scoped, only: :index

  def index
    @phone_numbers = policy_scope(PhoneNumber.all)
    fresh_when etag: [I18n.locale, current_user, cache_key_for_all(PhoneNumber)]
  end

  def show
    fresh_when etag: [I18n.locale, current_user, @phone_number]
  end

  def new
    @phone_number = PhoneNumber.new
    authorize @phone_number, :new?
  end

  def edit
  end

  def create
    @phone_number = PhoneNumber.new(phone_number_params)
    authorize @phone_number, :create?

    if @phone_number.save
      redirect_to @phone_number, notice: 'Phone number was successfully created.'
    else
      render :new
    end
  end

  def update
    if @phone_number.update(phone_number_params)
      redirect_to @phone_number, notice: 'Phone number was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @phone_number.destroy
    redirect_to phone_numbers_url, notice: 'Phone number was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_and_authorize_phone_number
      @phone_number = PhoneNumber.find(params[:id])
      authorize @phone_number, "#{action_name}?".to_sym
    end

    # Only allow a trusted parameter "white list" through.
    def phone_number_params
      params.require(:phone_number).permit(:name, :value, :phone_numberable_id, :phone_numberable_type)
    end
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/phone_numbers/_form.html.erb
<%= form_for @phone_number, html: { class: "pure-form pure-form-aligned" } do |f| %>
  <% if @phone_number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phone_number.errors.count, "error") %> prohibited this phone_number from being saved:</h2>

      <ul>
      <% @phone_number.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </fieldset>
  <fieldset>
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </fieldset>
  <fieldset>
    <%= f.label :phone_numberable_id %><br>
    <%= f.text_field :phone_numberable_id %>
  </fieldset>
  <fieldset>
    <%= f.submit class: "pure-button pure-button-primary" %>
  </fieldset>
<% end %>

app/views/phone_numbers/edit.html.erb
<h1>Editing Phone Number</h1>

<%= render 'form' %>

app/views/phone_numbers/index.html.erb
<% cache [I18n.locale, current_user, cache_key_for_all(PhoneNumber)] do %>
  <h1>Listing Phone Numbers</h1>

  <table class="pure-table pure-table-horizontal">
    <thead>
      <tr>
          <th>Name</th>
          <th>Value</th>
          <th>Phone numberable</th>
          <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @phone_numbers.each do |phone_number| %>
        <tr>
            <td><%= phone_number.name %></td>
            <td><%= phone_number.value %></td>
            <td><%= phone_number.phone_numberable %></td>
            <td><%= link_to 'Show', phone_number, class: policy(phone_number).show? ? 'pure-button':'pure-button pure-button-disabled' %></td>
          <td><%= link_to 'Edit', edit_phone_number_path(phone_number), class: policy(phone_number).edit? ? 'pure-button':'pure-button pure-button-disabled' %></td>
          <td><%= link_to 'Destroy', phone_number, method: :delete, data: { confirm: 'Are you sure?' }, class: policy(phone_number).destroy? ? 'pure-button':'pure-button pure-button-disabled' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Phone number', new_phone_number_path, class: policy(PhoneNumber.new).new? ? 'pure-button':'pure-button pure-button-disabled' %>
<% end %>

app/views/phone_numbers/new.html.erb
<h1>New Phone Number</h1>

<%= render 'form' %>

app/views/phone_numbers/show.html.erb
<% cache [I18n.locale, current_user, @phone_number] do %>
  <table class="pure-table pure-table-horizontal">
    <tbody>
        <tr>
        <td><strong>Name:</strong></td>
        <td><%= @phone_number.name %></td>
      </tr>
        <tr>
        <td><strong>Value:</strong></td>
        <td><%= @phone_number.value %></td>
      </tr>
        <tr>
        <td><strong>Phone numberable:</strong></td>
        <td><%= @phone_number.phone_numberable %></td>
      </tr>
      </tbody>
  </table>
<% end %>