config/routes.rb
Rails.application.routes.draw do
  resources :phone_numbers

  resources :schools

  resources :cities

  resources :periods

  resources :holidays

  get 'page/index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :federal_states

  resources :countries

  root 'page#index'

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="pure-menu pure-menu-horizontal pure-menu-open">
    <ul>
      <li><a href="http://amooma.de/">AMOOMA GmbH</a></li>
      <li><a href="https://github.com/wintermeyer/www.mehr-schulferien.de/">GitHub Repository</a></li>
    </ul>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

app/views/layouts/_topnavbar.html.erb
<div class="header">
  <div class="pure-menu pure-menu-open pure-menu-horizontal">
    <%= link_to 'Mehr Schulferien', root_path, class: 'pure-menu-heading' %>
    <ul>
      <li><%= link_to 'countries', countries_path, :class => current_page?(countries_path) ? "pure-menu-selected" : "" %></li>
      <li><%= link_to 'federal_states', federal_states_path, :class => current_page?(federal_states_path) ? "pure-menu-selected" : "" %></li>
      <% if current_user %>
      <li>
        Signed in as <strong><%= current_user.name %></strong>.
      </li>
      <li>
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      </li>
      <% else %>
      <li>
        <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>WwwMehrSchulferienDe</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div>
    <%= render partial: 'layouts/topnavbar' %>

    <div class="content pure-g">
      <div class="pure-u-4-5">

        <p id="notice"><%= notice %></p>
        <p id="error"><%= flash[:error] %></p>

        <%= yield %>

        <%= render partial: 'layouts/footer' %>
      </div>
      <div class="pure-u-1-5">
        <%= render partial: 'layouts/sidebar' %>
      </div>
    </div>
  </div>
</body>
</html>